### PR TITLE
[complete] Limit the maximum number of candidates

### PR DESCRIPTION
**Pull request by alexander-yakushev**
Addresses #588.

### CODE REVIEW

**Comment by cichli** [comment]
Thanks! I think it's sensible but maybe 100 is an order of magnitude too conservative, considering some frontends like Company and Ivy make it convenient to search candidates. For example, `clojure.core` has 659 publics in 1.10, and I'd expect to have them all available when completing `clojure.core/`. I think we should optimise this limit so that the JVM-side of things (including encoding the response) still performs acceptably. If there are problems on the client above a certain number of candidates, we can also do some limiting there.

One other thing though: the stacktrace in the linked issue points to [where the candidates are sorted](https://github.com/alexander-yakushev/compliment/blob/master/src/compliment/core.clj#L86-L92) in Compliment. Should we limit the number of candidates there (and likewise in cljs-tooling) before sorting them?

**Comment by alexander-yakushev** [comment]
Damn, you are absolutely right on both points. I'll make the necessary changes to Compliment instead.

**Comment by cichli** [comment]
I wonder if Compliment could also be a bit smarter about where the limit is applied. Maybe it's only needed for the keyword completions, at least until someone complains about performance in other cases :-).

**Comment by bbatsov** [comment]
Yeah, that's a good point. Alternatively we can expose the ability to set the limit in the query, so users can do whatever they want.

**Comment by bbatsov** [comment]
@alexander-yakushev So what are we doing with this PR?

**Comment by bbatsov** [comment]
@alexander-yakushev ping 2 :-)

**Pull request closed without merging**
