### PR TITLE
Include source/line/column in location info

### PR DESCRIPTION
**Pull request by j-mckitrick**
@bbatsov @Malabarba @jeffvalk 

Here's the first round of changes to return location info.

### CODE REVIEW

**Comment by Malabarba** [comment]
Looks fine from here.

(for reference: clojure-emacs/cider#715)

**Comment by bbatsov** [comment]
:+1: Looks fine to me as well.

**Comment by j-mckitrick** [comment]
So the next step will be pulling those bits up into emacs. I've done a bit
of elisp but very little navigation. What steps would you suggest next?

**Comment by Malabarba** [comment]
I think the next might be changing `nrepl-make-response-handler` to take this `line` and `column` information (with `nrepl-dbind-response`) and pass it to the error handling function.

**Comment by bbatsov** [comment]
What's the state here? I seem to recall @j-mckitrick something along the lines that those changes were redundant, but forgot the details.

**Comment by j-mckitrick** [comment]
Yes, it looks like things should be handled purely on the emacs side.  I think @Malabarba might have had an idea where to do it.

**Comment by Malabarba** [comment]
I remember discussing this at some point, but my memory is not my forte. :P 
Hopefully I wrote my thoughts on a comment somewhere.

**Pull request closed without merging**
