### PR TITLE
Check test namespaces exist

### PR DESCRIPTION
**Pull request by phillord**
Addresses clojure-emacs/cider#1940

Before submitting a PR make sure the following things have been done:

- [x] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [ ] You've added tests to cover your change(s)
- [x ] All tests are passing
- [x ] The new code is not generating reflection warnings
- [ ] You've updated the readme (if adding/changing middleware)

Thanks!

### CODE REVIEW

**Comment by bbatsov** [comment]
The fix looks good, but I'd also some unit test.

**Comment by bbatsov** [comment]
It also seems that the middleware op calling this method is not wrapped in `try/catch` which should also be fixed.

**Comment by bbatsov** [comment]
@phillord ping :-)

**Comment by phillord** [comment]
Running a little bit behind schedule....

**Comment by phillord** [comment]
I'm not sure how to handle the exceptions further up. Most of the middleware handlers seem to use `with-safe-transport` which looks like the thing, although some (`wrap-refresh`) do not. I don't really understand this code in any depth. Am I on the right track with with-safe-transport? And if so, does `wrap-refresh` and some of the others need exception handling as well?

**Comment by bbatsov** [comment]
> I'm not sure how to handle the exceptions further up. Most of the middleware handlers seem to use with-safe-transport which looks like the thing, although some (wrap-refresh) do not. I don't really understand this code in any depth. Am I on the right track with with-safe-transport? And if so, does wrap-refresh and some of the others need exception handling as well?

You're on the right path - if you take a look at the code of `with-safe-transport` it simply adds some exception handling logic. If something goes wrong it would send an error reply which CIDER can present to the user. Probably it's an oversight that some middleware don't use it.  

@sanjayl added this to simplify the code repetition we had before. Details here https://github.com/clojure-emacs/cider-nrepl/commit/9a81e27dcea44457b1670f4dfd8895e1e772f658

**Comment by sanjayl** [comment]
I'm not sure if `with-safe-transport` will work with this as currently written because the `msg` map is being altered [during the creation of the handler](https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/test.clj#L299-L309). The `with-safe-transport` macro doesn't have a mechanism to accept modifications to the `msg` at handler-creation time.

**Comment by bbatsov** [comment]
OK, guess I'll merge as is for now. A fix is better than no fix. :-)

**Comment by phillord** [comment]
Oh, okay. I hadn't finished, but never mind.

**Pull request merged**
