### PR TITLE
Fully evaluate lazy seqs when macroexpanding

### LINKED ISSUE #886: Macroexpansion with lazy seqs occurs in the wrong ns
## Expected behavior
Cider-nrepl's `macroexpansion` op should produce the same output as manually calling `macroexpand`.

## Actual behavior
If the macro definition contains lazily evaluated seqs, their contents will be evaluated with the wrong dynamic *ns* bindings (in the `user` ns), which can result in incorrect / misleading expansions.

## Steps to reproduce the problem
```clj
(ns repro)

(defmacro lazy []
  (cons (ns-name *ns*)
        (lazy-seq [(ns-name *ns*)])))

(macroexpand '(lazy))
;; => (repro repro)

(lazy) ;; <- M-x cider-macroexpand: (repro user)
```

### cider-nrepl version
0.49.1

### Java version

21.0.1

### Operating system

MacOS 14

### PR DESCRIPTION
**Pull request by yuhan0**
Fixes #886

Note: I also added a `doall` in what seemed like the right spot for the cljs expander, but wasn't able to easily test whether it had any effect. There's no existing test coverage for that code path so I'm fine with removing it in case it breaks anything.

---
Before submitting a PR make sure the following things have been done:

- [x] The commits are consistent with our [contribution guidelines](../blob/master/.github/CONTRIBUTING.md)
- [x] You've added tests to cover your change(s)
- [x] All tests are passing
- [ ] You've updated the README
- [ ] Middleware documentation is up to date
  * Please check out and modify the `cider.nrepl` ns which has all middleware documentation.
  * Run `lein docs` afterwards, and commit the results.

Thanks!

### CODE REVIEW

**Review by vemv — APPROVED** [review]
Thanks!

LGTM

**Comment by yuhan0** [comment]
Oh.. I only ran `lein test`, good thing the CI caught this bug.  Somehow I couldn't replicate the test failure locally using `make tools-deps-test` but hopefully the following commit should fix it.

**Comment by alexander-yakushev** [comment]
Unfortunately, it is not enough to call `doall` to force all internal parts of the constructed sexp. See https://clojure-goes-fast.com/blog/clojures-deadly-sin/#no-way-to-force-everything.

Try making a test case where the lazy part of the macro is somewhere deeper in the top-level expression. I think you'll have to `print-str` or something like that.

**Comment by alexander-yakushev** [comment]
This PR is superseded by #894 which should handle the lazy expansion problem fully besides other things.

**Comment by alexander-yakushev** [comment]
@yuhan0 Thanks for reporting the issue and proposing a fix! This led to uncovering a deeper problem with macroexpansion middleware.

**Pull request closed without merging**
