### PR TITLE
Debugger fix for the new inspector pagination

### PR DESCRIPTION
**Pull request by Malabarba**

### CODE REVIEW

**Comment by bbatsov** [comment]
Hmm, there's some strange test failure.

**Comment by Malabarba** [comment]
Yes, I saw it. Haven't been able to look at it yet.

**Comment by Malabarba** [comment]
Oh, that's just a cljfmt bug. The indentation is correct. 
I filed an issue and it's fixed, so maybe we need to bump the version used by the test?

**Comment by bbatsov** [comment]
Yeah, we should do this.

**Comment by expez** [comment]
I've bumped both the version used in the test as well as the dep used for formatting code.  Go ahead and rebase @Malabarba

**Comment by expez** [comment]
Any idea if `:cljfmt {:indents {as-> [[:inner 0]]}}` is still needed?  cljfmt doesn't have a changelog.

**Comment by Malabarba** [comment]
Rebased

**Comment by Malabarba** [comment]
> Any idea if :cljfmt {:indents {as-> [[:inner 0]]}} is still needed? cljfmt doesn't have a changelog.

No idea. =/

**Comment by bbatsov** [comment]
:+1:

**Pull request merged**
