### PR TITLE
set version to 0.10.2

### PR DESCRIPTION
**Pull request by cap10morgan**

### CODE REVIEW

**Comment by bbatsov** [comment]
Please capitalize the commit message's title.

**Comment by cap10morgan** [comment]
Will do, sorry. Going to take me forever to get used to that. ;)

**Comment by bbatsov** [comment]
Seems I was mistaken. There are some bugfixes here I forgot about:

https://github.com/clojure-emacs/cider-nrepl/commit/866a451119684b2ba96d82120e021edc19068c65
https://github.com/clojure-emacs/cider-nrepl/commit/e324c2bc8acdbca845defbf7a2187054790c3e57
https://github.com/clojure-emacs/cider-nrepl/commit/52e0f86fdb8f85c41a2981ba85aefafe6fa1039f
https://github.com/clojure-emacs/cider-nrepl/commit/ef6711a2f6dd8af42a6968ca8d6a9736c12a2cad
https://github.com/clojure-emacs/cider-nrepl/commit/921d85050ea3cc3bb79472b822c8bddf8c3a63c2
https://github.com/clojure-emacs/cider-nrepl/commit/09ca7be44468373e9ef9126da40320e03649cfef

**Comment by cap10morgan** [comment]
OK, I'll get those backported and PR'd.

**Pull request merged**
