### PR TITLE
Minimize string formatting in `format-spec`

### PR DESCRIPTION
**Pull request by xiongtx**
Part of clojure-emacs/cider#2150

Let CIDER take care of as much formatting as possible.

### CODE REVIEW

**Comment by bbatsov** [comment]
Doesn't changing those functions affect any tests?

**Comment by xiongtx** [comment]
Unfortunately it seems [CI has been broken for some time](https://travis-ci.org/clojure-emacs/cider-nrepl/builds). But it seems the failures are not related to this change, but from:

```
FAIL in (step-in-to-function-in-current-project-test) (debug_integration_test.clj:495)
step in
Message: {:debug-value "\"bar\"", :original-ns "cider.nrepl.middleware.util.misc", :key "48460051-82d8-4ee1-9230-130e1794a36d", :locals [["x" "\"bar\""]], :file "file:/home/txx/github/cider-nrepl/src/cider/nrepl/middleware/util/misc.clj", :column 0, :input-type {:q "quit", :o "out", :n "next", :e "eval", :s "stacktrace", :l "locals", :c "continue", :j "inject", :h "here", :t "trace", :p "inspect", :i "in"}, :prompt [], :coor [3 1 1], :line 37, :status ["need-debug-input"], :id 62, :code "(defn as-sym\n  [x]\n  (cond\n    (symbol? x) x\n    (string? x) (if-let [[_ ns sym] (re-matches #\"(.+)/(.+)\" x)]\n                  (symbol ns sym)\n                  (symbol x))))", :original-id 65, :session "cb583e4b-4918-4504-94c1-1f7bc3dbd975"}
expected: (clojure.core/= 32 (clojure.core/get msg6989 :line))
  actual: (not (clojure.core/= 32 37))
```

You can see this from [failures in previous builds](https://travis-ci.org/clojure-emacs/cider-nrepl/jobs/323618768).

**Comment by bbatsov** [comment]
Yeah, I've been meaning to look into this broken test for a while now, but had 0 time for this.

I actually meant something else - I was surprised that changing this didn't break any of this middleware's tests. First I thought you forgot about the tests, but I guess there were no tests for the formatted result.

**Comment by xiongtx** [comment]
The breaking test is fixed in #467.

**Comment by bbatsov** [comment]
Thanks! 🙇

**Pull request merged**
