### PR TITLE
[Fix #449] Bump mranderson version

### LINKED ISSUE #449: Can't build cider-nrepl with lein 2.8.0: source-deps task is broken
## Expected behavior
When building cider-nrepl from source using leiningen 2.8.0, one should be able to build inline deps with the manderson plugin, as per https://github.com/clojure-emacs/cider-nrepl#working-with-mranderson-inlining-dependencies. Works with lein 2.7.1:
```
$  lein source-deps :project-prefix cider.inlined-deps
project prefix:  cider.inlined-deps
retrieve dependencies and munge clojure source files
  retrieving tools.trace artifact.
...
```
## Actual behavior
With lein 2.8.0, building source deps fails:
```
$  lein source-deps :project-prefix cider.inlined-deps
java.lang.ClassCastException: Cannot cast org.apache.maven.repository.internal.DefaultVersionResolver to org.sonatype.aether.impl.VersionResolver
        at java.lang.Class.cast(Class.java:3369)
        at org.sonatype.aether.impl.internal.DefaultServiceLocator.getServices(DefaultServiceLocator.java:161)
        at org.sonatype.aether.impl.internal.DefaultServiceLocator.getService(DefaultServiceLocator.java:133)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.initService(DefaultRepositorySystem.java:142)
        at org.sonatype.aether.impl.internal.DefaultServiceLocator.getServices(DefaultServiceLocator.java:181)
        at org.sonatype.aether.impl.internal.DefaultServiceLocator.getService(DefaultServiceLocator.java:133)
        at mranderson047.pomegranate.v0v3v0.cemerick.pomegranate.aether$repository_system.invokeStatic(aether.clj:110)
        at mranderson047.pomegranate.v0v3v0.cemerick.pomegranate.aether$repository_system.invoke(aether.clj:108)
        at mranderson047.pomegranate.v0v3v0.cemerick.pomegranate.aether$resolve_dependencies_STAR_.invokeStatic(aether.clj:691)
...
```
which causes additional exceptions, see [stacktrace.txt](https://github.com/clojure-emacs/cider-nrepl/files/1425867/stacktrace.txt)

This seems like a classpath issue, as leiningen changed it's dependencies from 2.7.1 -> 2.8.0. I couldn't fix the problem with a first-order attempt at fiddling with exclusions and forced versions, but someone who knows how manderson/pomegranate/aether/maven/leiningen interact might. Once this is figured out, it would be nice to add a `:pedantic? :abort` entry to the build as well.

### cider-nrepl version

0.16.0-SNAPSHOT @ ce42411

### Java version

openjdk 1.8.0_131

### Operating system

Debian 4.9.30-2+deb9u2

### PR DESCRIPTION
**Pull request by benedekfazekas**
to fix leiningen 2.8.x incompatibility issues

### CODE REVIEW

**Comment by benedekfazekas** [comment]
hm... mranderson part is working now but failing still. will have an other look tmrw

**Comment by bbatsov** [comment]
Roger that!

I don't even get how bumping the leiningen version can affect something in nREPL (which seems to be the case, given the staketrace).

**Comment by benedekfazekas** [comment]
the famous "works for me": tests are passing on my local machine (java8, lein 2.8.1)

**Comment by bbatsov** [comment]
I restarted the build but everything fails again. I've got no time to investigate this further.

**Comment by bbatsov** [comment]
I've noticed we're getting the same failures on another PR, so I guess I can merge this. Seems something else is messed up.

**Pull request merged**
