### PR TITLE
Bump compliment to 0.3.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by cskksc**
~~I still couldn't get the auto-complete to work for the form, `(resource "|")`. But that is an additional feature and does not block this upgrade. Everything else works.
I'm working on it and we can add that later. It wouldn't require any changes to the middleware.~~

- [ ] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [ ] You've added tests to cover your change(s)
- [ ] All tests are passing
- [ ] The new code is not generating reflection warnings
- [ ] You've updated the readme (if adding/changing middleware)

Thanks!

/cc @alexander-yakushev

### CODE REVIEW

**Comment by cskksc** [comment]
Sorry for the confusion. I was thinking that a new `resources` source has been added in 0.3.
But we always had that. It's just that we do not yet parse the context which it expects. That is not related to this upgrade at all.

**Comment by bbatsov** [comment]
Looks good to me, but I'll wait to hear what @alexander-yakushev thinks about the changes as well.

**Comment by alexander-yakushev** [comment]
Looks fine except for the fact that some test are failing :).

**Comment by cskksc** [comment]
The `debug-integration-tests` have failed. They are a bit flaky on travis :-). All the tests were passing on my local machine.

**Comment by alexander-yakushev** [comment]
Let's merge it then.

**Comment by bbatsov** [comment]
A couple of tests are failing locally for me:

```
FAIL in (complete) (complete_test.clj:13)
blank
expected: (= #{"done"} (:status response))
  actual: (not (= #{"done"} #{"complete-error" "done"}))

lein test :only cider.nrepl.middleware.complete-test/complete

FAIL in (complete) (complete_test.clj:14)
blank
expected: (sequential? (:completions response))
  actual: (not (sequential? nil))
```

Anyways, this is now deployed.

**Comment by cskksc** [comment]
I'll check again. But it's strange. Those tests have passed on travis.

**Pull request merged**
