### PR TITLE
Return cider-test result keys more specifically

### PR DESCRIPTION
**Pull request by cap10morgan**
This brings in commit a62f937 to be compatible with a bug fix going into cider 0.10.1.

### CODE REVIEW

**Comment by bbatsov** [comment]
@benedekfazekas Seems that the new mranderson doesn't work with Java 6, right?

**Comment by benedekfazekas** [comment]
It should work with a workaround, see our discussion here clojure-emacs/cider-nrepl#247

**Comment by bbatsov** [comment]
Yeah, I remembered this. Guess it's not important at all, as at the end of the day I create the jars under JDK8.

**Comment by bbatsov** [comment]
Probably this should be backported as well https://github.com/clojure-emacs/cider-nrepl/commit/6b7fcb8214cf455d2acf7a068eec9c316431d8ff

**Comment by bbatsov** [comment]
Hmm, I've got one failing test in the branch:

```
FAIL in (test-cause-data-pretty-printing) (stacktrace_test.clj:110)
compilation errors
expected: (re-find #"Error compiling: .* Unable to resolve symbol: not-defined in this context" (:message (first causes3)))
  actual: (not (re-find #"Error compiling: .* Unable to resolve symbol: not-defined in this context" "Unable to resolve symbol: not-defined in this context"))
```

However, I cut the release, as I didn't have time to investigate - hopefully it's nothing major.

**Comment by bbatsov** [comment]
Damn, just looked at the build - everything is failing.

**Comment by jeffvalk** [comment]
@bbatsov This commit broke a test. I didn't notice that until just now because @cichli had already fixed the test in fbbd3038254bac4cfa2a5493b3657423130e70ac. If you pull in that commit, things should be good.

**Comment by cap10morgan** [comment]
I opened a PR with that commit on the v0.10 branch: #283

**Pull request merged**
