### PR TITLE
Move transform-value from the orchard to cider-nrepl

### PR DESCRIPTION
**Pull request by arichiardi**
The transform-value function is moved here to cider-nrepl, where it belongs, as
it seems to be mainly related to presentation only.

PR friend of https://github.com/clojure-emacs/orchard/pull/66 

Before submitting a PR make sure the following things have been done:

- [X] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [X] All tests are passing
- [X] The new code is not generating reflection warnings

### CODE REVIEW

**Comment by bbatsov** [comment]
I think an `output` ns is a bit misleading as it generally makes you think about console/file output. This used to be in the main util ns in the past and probably we should add it back there.

**Comment by arichiardi** [comment]
Ok I will put it there then, thank you!

**Comment by arichiardi** [comment]
Ok addressed the comment.

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
