### PR TITLE
Fix print-length bug and fix integration tests

### PR DESCRIPTION
**Pull request by alexander-yakushev**
All of the useful work was done in clojure-emacs/orchard#24.

Not editing CHANGELOG here since nothing useful happened in cider-nrepl. I can, however, edit the CHANGELOG in cider if you like, since changes in Orchard are user-facing.

### CODE REVIEW

**Comment by bbatsov** [comment]
> Not editing CHANGELOG here since nothing useful happened in cider-nrepl. I can, however, edit the CHANGELOG in cider if you like, since changes in Orchard are user-facing.

👍 

Btw, I see the tests of the inspector broke on cljs. I guess you should look into this.

**Comment by alexander-yakushev** [comment]
My bad, I forgot about CLJS. How do I properly run its tests? `lein with-profiles +test-cljs test` fails for me for existing tests, e.g.:

```
FAIL in (cljs-complete-test) (cljs_complete_test.clj:40)
macro metadata
expected: (string? (:doc candidate))
  actual: (not (string? nil))
Exception in thread "nREPL-worker-1" java.lang.NullPointerException
	at cljs.repl.node.NodeEnv._tear_down(node.clj:187)
	at cemerick.piggieback$evaluate.invoke(piggieback.clj:264)
	at clojure.lang.Var.invoke(Var.java:379)
	at cemerick.piggieback$wrap_cljs_repl$fn__6025$fn__6027$fn__6028.invoke(piggieback.clj:291)
	at cemerick.piggieback$enqueue$fn__6011.invoke(piggieback.clj:247)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__859.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bbatsov** [comment]
I run them like this: `lein with-profile +1.8,+test-cljs test`.

**Comment by alexander-yakushev** [comment]
Still fails with the same error.

**Comment by bbatsov** [comment]
I ran the tests locally and I got exactly the same results as on the CI. I guess something's different in your setup, but I have no idea what. My lein is 2.8.1.

**Comment by alexander-yakushev** [comment]
Perhaps, my `profiles.clj` is to blame. Anyway, I've fixed the tests, should be mergeable as soon as Travis finishes.

**Comment by alexander-yakushev** [comment]
Aaaand it failed with a timeout in one cell of the matrix. Safe to be merged, I guess.

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
