### PR TITLE
Bump cljs-tooling dep to 0.1.4

### PR DESCRIPTION
**Pull request by cichli**

### CODE REVIEW

**Comment by bbatsov** [comment]
The build failure seems unrelated.

**Comment by cichli** [comment]
Yeah, I saw the same failure when playing around with a branch that caches `$HOME/.m2` on Travis. Seems like there's a problem with `org.clojure:clojure:jar:1.7.0-master-SNAPSHOT`? I presumed it was related to the caching changes but maybe not. The only workaround I found was to use the latest alpha instead of SNAPSHOT: https://github.com/clojure-emacs/cider-nrepl/compare/master...cichli:cache-m2#diff-0fff143854a4f5c0469a3819b978a483

**Comment by bbatsov** [comment]
Maybe re-triggering the build will fix this?

**Comment by cichli** [comment]
You can do this in the Travis web UI now - there should be a refresh button in the top right of https://travis-ci.org/clojure-emacs/cider-nrepl/builds/52208362. Otherwise I'll force push again when I get home this evening.

I kicked the job for my fork off again and it [failed in the same way](https://travis-ci.org/cichli/cider-nrepl/jobs/52208346).

**Comment by cichli** [comment]
FWIW if I remove `~/.m2/` and run `lein with-profile +1.7 test` I see the same problem.

**Comment by cichli** [comment]
I've [posted](https://groups.google.com/forum/#!topic/clojure/S-u1ijNMUl4) on the mailing list regarding this.

**Pull request closed without merging**
