### PR TITLE
[Fix clojure-emacs/cider#1825] Capture test input

### PR DESCRIPTION
**Pull request by sebastianpoeplau**
We now capture test input as generated by `test.check` and pass it on to
cider_test.el for display.

### CODE REVIEW

**Comment by sebastianpoeplau** [comment]
It seems that the test that is failing here also fails on the latest master...

**Comment by bbatsov** [comment]
LGTM. Thanks!

@Malabarba can you push to clojars? I don't have my workhorse with me. :-)

**Comment by Malabarba** [comment]
I can push on Monday. I don't have my workhorse during the weekends. :-/

**Comment by Malabarba** [comment]
Done :+1:

**Pull request merged**
