### PR TITLE
Make inspect command work on current expression, add inspect-prompt 

### PR DESCRIPTION
**Pull request by yuhan0**
Credit goes to @alexander-yakushev in #613 :)

- [x] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [x] You've added tests to cover your change(s)
- [x] All tests are passing
- [x] The new code is not generating reflection warnings
- [x] You've updated the README (if adding/changing middleware)

### CODE REVIEW

**Comment by yuhan0** [comment]
Oh, but now the commit message and changelog doesn't line up with the actual change, not sure if I can edit that without overwriting authorship

**Comment by bbatsov** [comment]
@yuhan0 Just add a second commit that changes this.

**Comment by yuhan0** [comment]
It turns out I could squash the previous commit without overwriting authorship info, learnt something new about Git :)

**Comment by bbatsov** [comment]
Great! I'll push a new snapshot out.

**Comment by alexander-yakushev** [comment]
🥳
Thanks, @yuhan0 and @bbatsov!

**Pull request merged**
