### PR TITLE
Some improvements to intrument.clj

### PR DESCRIPTION
**Pull request by Malabarba**
Amonst other things, this addresses the issues on raised on #170 with `do` and `recur`.

### CODE REVIEW

**Comment by Malabarba** [comment]
There's something wrong with the date on the commits, and they're listed out of order above. The final commit is the "Improve support for ...".

**Comment by Malabarba** [comment]
I keep running into discrepancies between clojure-mode's indentation and cljfmt. Should I file these to the former or the latter?

**Comment by bbatsov** [comment]
> I keep running into discrepancies between clojure-mode's indentation and cljfmt. Should I file these to the former or the latter?

Depends on the issue. Can you post the differences here?

**Comment by Malabarba** [comment]
For reference, this should Close https://github.com/clojure-emacs/cider/issues/1048

**Comment by Malabarba** [comment]
> Depends on the issue. Can you post the differences here?

The following snippet is indented as an `fn` by `clojure-mode`, but
it's indented as a regular function call by cljfmt.

    ;; cljfmt
    `(~'fn [~'x]
          (~'if ...))
    
    ;; clojure-mode
    `(~'fn [~'x]
       (~'if ...))

And the indentation for the `are` macro is different too:

    ;; cljfmt
    (are [f] (= 1 (#'t/specifier-match-bindings f))
        '([] sherlock))
        
    ;; clojure-mode
    (are [f] (= 1 (#'t/specifier-match-bindings f))
      '([] sherlock))

**Comment by bbatsov** [comment]
Regarding the indentation - the first situation is debatable, the second not so much. The indentation in `clojure-mode` is definitely the correct one.

**Comment by Malabarba** [comment]
Oops. Fixed the period.
And sorry, I got all mixed up with the indentations thing. The `are` macro examples are swapped.

This is `clojure-mode`

    (are [x] (#'t/listy? x)
        '()
        `()
        '(a))

This is `cljfmt`

    (are [x] (#'t/listy? x)
      '()
      `()
      '(a))

**Comment by bbatsov** [comment]
:+1:

**Pull request merged**
