### PR TITLE
Send test coverage data to coveralls.io

### PR DESCRIPTION
**Pull request by cichli**
I thought this was pretty cool - see what the reports look like [here](https://coveralls.io/r/cichli/cider-nrepl) or for a specific file [here](https://coveralls.io/files/527870364). It doesn't support partial line coverage (see lemurheavy/coveralls-public#216) so cloverage uses 1x line hit for partial coverage and 2x line hits for complete coverage.

PRs will have an extra status added with information on how test coverage has changed if you enable coveralls for the repo at http://coveralls.io (only needs status API permissions).

### CODE REVIEW

**Comment by bbatsov** [comment]
I'm familiar with `coveralls` - I use it in various Ruby projects. There's a useful badge that we might add to the README. It shows the current coverage.

**Comment by cichli** [comment]
I've added a badge next to the Travis badge in README.md.

**Comment by bbatsov** [comment]
:+1:

**Comment by cichli** [comment]
Now to make that number go down :-). If you browse to [a file](https://coveralls.io/files/530587217) in the report it can't find the source - think you need to tell coveralls the the paths are relative to /src/ on that page.

**Comment by bbatsov** [comment]
Done.

On 9 March 2015 at 20:42, Michael Griffiths <notifications@github.com>
wrote:

> Now to make that number go down :-). If you browse to a file
> <https://coveralls.io/files/530587217> in the report it can't find the
> source - think you need to tell coveralls the the paths are relative to
> /src/ on that page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider-nrepl/pull/167#issuecomment-77916064>
> .
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Pull request merged**
