### PR TITLE
Abbreviate printing of some objects

### PR DESCRIPTION
**Pull request by Malabarba**
Instead of printing as
`  #object[clojure.core$_PLUS_ 0x4e648e99 "clojure.core$_PLUS_@4e648e99"]`
they are now printed as
`  #function clojure.core/+`

### CODE REVIEW

**Comment by bbatsov** [comment]
That's a welcome change, but it will probably be more valuable if we apply it to eval results in general - by this I mean changing the eval results in case when something returns a var. I mentioning this, because of we update it only in the output there would inconsistency between the output and the eval results.

**Comment by Malabarba** [comment]
eval results are converted to strings via the print-method method. So they are already affected by this.

**Comment by bbatsov** [comment]
> eval results are converted to strings via the print-method method. So they are already affected by this.

Good to know. So, this should probably be out of the `out` middleware then. I'd normally expect to have only stuff directly related to the middleware there (which prompted my original comment).

**Comment by Malabarba** [comment]
Where do you think it could go? 
If I  create a new file for it, I think I'll have to do some configuring to make sure it's loaded.

**Comment by bbatsov** [comment]
Not sure actually. My biggest concern is that some people might want to turns off the middleware without the custom printing or vice versa and as it stands - they can't do so.

**Comment by Malabarba** [comment]
I think I'll put it in a file called `print-method.clj` *outside* the `middleware` directory (since it's actually not a middleware). And I'll define a variable for disabling this.

**Comment by bbatsov** [comment]
Sounds good.

**Comment by Malabarba** [comment]
Done. ADded tests and method support

**Comment by Malabarba** [comment]
Alright if I merge this?

**Comment by bbatsov** [comment]
Allow me. :-)

**Pull request merged**
