### PR TITLE
Rename `nrep.clj` to `nrepl.clj`

### LINKED ISSUE #416: `nrep.clj` should be `nrepl.clj`
## Expected behavior

[`src/cider/nrepl/middleware/util/nrep.clj`](https://github.com/clojure-emacs/cider-nrepl/commit/ec4de412a9f14b8b03d9e2de128f50346d356f34) should be `.../nrepl.clj` instead.

## Actual behavior

`nrep.clj` is clearly a typo--the ns is `cider.nrepl.middleware.util.nrepl`.

## Steps to reproduce the problem

N/A

### PR DESCRIPTION
**Pull request by xiongtx**
Fixes #416.

### CODE REVIEW

**Comment by xiongtx** [comment]
@benedekfazekas Surely [this build failure](https://travis-ci.org/clojure-emacs/cider-nrepl/jobs/247374472) has something to do w/ `mranderson`? 

```
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate mranderson047/toolsnamespace/v0v3v0_alpha3/clojure/tools/namespace/parse__init.class or mranderson047/toolsnamespace/v0v3v0_alpha3/clojure/tools/namespace/parse.clj on classpath: , compiling:(mranderson047/toolsnamespace/v0v3v0_alpha3/clojure/tools/namespace/file.clj:1:1)
 at clojure.lang.Compiler.load (Compiler.java:7142)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    ...
```

**Comment by benedekfazekas** [comment]
will have a look

**Comment by benedekfazekas** [comment]
sorry for the late reply.

this is again a red herring, sorry for disappointing ;)

there is this exception in every build before the right version of lein is set by the build script. but this  does not fail the build afaik. the above build failure is due to some test fails i guess...

suppose bozhidar came to the same conclusion as he merged the above wo second thoughts...

**Comment by xiongtx** [comment]
Regardless, it should be fixed. I don't quite understand the issue--does the build script need to be changed to set the right version of Lein earlier in the process?

**Comment by benedekfazekas** [comment]
I guess it is related to this travis issue https://github.com/travis-ci/travis-ci/issues/4791
as it got closed at some point i guess i will read through the comments at some point and figure out if there is a proper solution now.

**Comment by benedekfazekas** [comment]
very likely this https://docs.travis-ci.com/user/languages/clojure#Using-a-more-recent-versions-of-Leiningen is the solution...

ok gave this a quick try. did not quite work. will need to dig into this deeper...

**Comment by benedekfazekas** [comment]
cracked it. thx @xiongtx for pushing for it ;)

**Pull request merged**
