### PR TITLE
Instrument def with docstring for debugging

### PR DESCRIPTION
**Pull request by grammati**
Previously, instrumentation would drop the value expression, and the
docstring docstring would become the value.

### CODE REVIEW

**Comment by Malabarba** [comment]
Good catch. The code looks good! :+1: 

Why coveralls reports a coverage decrease when you literally changed a `second` to a `rest` **and** actually added tests is beyond me.

**Comment by bbatsov** [comment]
Looks good. Just remove the `.` from the commit message's title (as titles are not sentences as far as I'm concerned).

**Comment by grammati** [comment]
Commit message updated.

**Comment by bbatsov** [comment]
:+1: 10x!

**Pull request merged**
