### PR TITLE
Fix delayed middleware loading issue

### PR DESCRIPTION
**Pull request by Cartmanishere**
Hi,

This is an attempt to fix issue around delayed middleware loading.
The relevant discussion is present at https://github.com/clojure-emacs/cider-nrepl/issues/533 

Instead of adding the handler delay to the `delayed-handlers` atom in the macro, this takes care of adding
it in the atom through a function. 

Fixes:
https://github.com/clojure-emacs/cider-nrepl/issues/447
https://github.com/clojure-emacs/cider-nrepl/issues/533
https://github.com/clojure-emacs/cider-nrepl/issues/657

### CODE REVIEW

**Comment by Cartmanishere** [comment]
Test for this are failing. The failures seem related to `cljs` and are not caused by the changes in this PR.

**Comment by bbatsov** [comment]
Did you manage to confirm that the suggested fix solves the race conditions? //cc @vspinu 

Also - this needs a changelog entry. 

> Test for this are failing. The failures seem related to cljs and are not caused by the changes in this PR.

Yeah, there's a ticket for this #678 but I haven't been able to find time to investigate things further.

**Comment by Cartmanishere** [comment]
This is not a race condition per se. The problem is that we are relying on compile time side effects to be present at runtime. This works in normal scenario but breaks when the middlewares are compiled from within an application. 

So to fix this, instead of relying on compile time side effects, we handle it at runtime. This fixes the issue. https://github.com/clojure-emacs/cider-nrepl/issues/447 has a reproducible example against which you can check.

**Comment by bbatsov** [comment]
Got it. Thanks for tackling this! 🙇‍♂️ I'll cut a new release right away, as that is an important fix.

**Comment by timvisher** [comment]
_This_ is seriously exciting. 😂

**Pull request merged**
