### PR TITLE
[Fix clojure-emacs/cider#1320] Do state tracking in a future

### PR DESCRIPTION
**Pull request by Malabarba**
This should fix all lags associated with the new namespace tracking,
both the long delay at first connection and the ~1sec lag in the REPL.

### CODE REVIEW

**Comment by bbatsov** [comment]
Won't an agent be a better fit for this?

**Comment by Malabarba** [comment]
Is it ok if the function used to update agents in not pure?

**Comment by expez** [comment]
I think you're risking retries when using agents, but if the only IO is reading from disk then that should be fine.

**Comment by bbatsov** [comment]
I think agents never trigger retries, so this should not be a concern. After all people are implementing log systems and things like this using agents. In a transaction an agent won't be executed until the transaction commits, but this is different.

**Comment by Malabarba** [comment]
I'm running some tests here, and it looks like agents do not trigger retries indeed.

    (def at (agent 0))
    (def c (atom 0))
    (do (dotimes [x 1000]
          (future (Thread/sleep 200)
                  (send at #(do (swap! c inc)
                                (inc %)))))
        (println @c))


This always prints `1000`. Whereas, if I replace `(agent 0)` with `(atom 0)` and replace `send` with `swap!` then I always get at least `1030`.

Not a super rigorous test, but it's convinced me. :)

**Comment by Malabarba** [comment]
https://clojurians.slack.com/archives/clojure/p1442501641001191

**Comment by expez** [comment]
I'm not on slack but I just looked at the implementation and you guys are indeed right.  There are no retries because the agent holds an `ActionQueue` internally.

**Comment by bbatsov** [comment]
So, it seems we have clarity here. Agent it is! :-)

**Comment by bbatsov** [comment]
Apart from the failing tests the code looks good to me.

**Pull request merged**
