### PR TITLE
Backported fixes for a 0.10.1 release

### PR DESCRIPTION
**Pull request by cap10morgan**
Here's my first cut at a conservative set of fixes on master since v0.10.0 was released. Let me know if I missed any that should be pulled in or pulled in anything that should be omitted.

### CODE REVIEW

**Comment by bbatsov** [comment]
:+1: Looks good!

**Comment by cichli** [comment]
Thanks for taking the initiative on this @cap10morgan! I have a couple more fixes to the macroexpansion middleware that were unfortunately all rolled into one commit 99065dd55deb96df1f7979baddabe67930ea741b - I'll tease out the relevant changes and apply them onto this branch.

It might be worth bumping the `mranderson` and `eastwood` deps too, to satisfy the CI.

**Comment by bbatsov** [comment]
> It might be worth bumping the mranderson and eastwood deps too, to satisfy the CI.

Yeah, we should do this.

**Comment by cichli** [comment]
> Yeah, we should do this.

I'll do it now.

**Comment by cichli** [comment]
I've bumped the mentioned versions and backported the macroexpansion fixes across (took a while to figure out why the build was failing on 1.6 until I remembered transducers were added in 1.7 :flushed:). The JDK6 builds are still failing for the same reason as before (seems like a mranderson issue). @bbatsov anything else to add to this branch, or do you want to cut the release?

**Comment by bbatsov** [comment]
There are some Emacs Lisp patches that have to be backported before we can
cut the release.

On Sunday, 27 December 2015, Michael Griffiths <notifications@github.com>
wrote:

> I've bumped the mentioned versions and backported the macroexpansion fixes
> across (took a while to figure out why the build was failing on 1.6 until I
> remembered transducers were added in 1.7 [image: :flushed:]). The JDK6
> builds are still failing for the same reason as before (seems like a
> mranderson issue). @bbatsov <https://github.com/bbatsov> anything else to
> add to this branch, or do you want to cut the release?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/cider-nrepl/pull/280#issuecomment-167415383>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Pull request merged**
