### PR TITLE
`fn-refs` and `fn-deps` middleware: offer `file-url` field

### PR DESCRIPTION
**Pull request by vemv**
Fixes https://github.com/clojure-emacs/cider-nrepl/issues/796

Cheers - V

### CODE REVIEW

**Comment by bbatsov** [comment]
I think cider is the only client of this functionality, so you don't really need the `file-format` option IMO and can simplify things a bit.

**Comment by vemv** [comment]
I agree and was on the fence about this one.

But I think it's a good thing to normalize "retro-compat" techniques - if we don't have the habit of using them, we'll forget about them when it matters?

Also, not impossible to have an odd cider/cider-nrepl combo. And it's good to leave the door open to alternative emacs-side xref impls.

e.g. I'm working on a https://github.com/clojure-emacs/cider/pull/3349 spin-off, but what if we decide to change the approach again a few months from now?

**Comment by bbatsov** [comment]
> But I think it's a good thing to normalize "retro-compat" techniques - if we don't have the habit of using them, we'll forget about them when it matters?

That's my bigger concern - I've never been fond of API versioning, so this `v2` bothers me a lot. (I'm fan of accretive changes, meaning I'd rather add new fields in the response than make it possible for the client to pick between versions) For me it's much simpler here to change this than to spend a lot of time discussing what's the best way to do `retro-compat`.

**Comment by vemv** [comment]
Alright! Adding a new field is a good choice as well.

**Comment by vemv** [comment]
Ready.

**Comment by vemv** [comment]
Added an extra commit to sort the results, especially for the line. Otherwise I was finding cider.el side that that for the same given file, results could be presented in an erratic order: line 50, 20, 80, etc.

**Review by bbatsov — APPROVED** [review]

**Comment by bbatsov** [comment]
Looks good me.

**Comment by vemv** [comment]
Thanks!

**Pull request merged**
