### PR TITLE
Use CircleCI for Continuous Integration

### PR DESCRIPTION
**Pull request by arichiardi**
This really is NOT my work but @shen-tian's :smile: 

Just applying it here.

### CODE REVIEW

**Comment by arichiardi** [comment]
I am building my master branch here: https://circleci.com/gh/arichiardi/workflows/cider-nrepl/tree/master

**Comment by bbatsov** [comment]
Thanks for tackling this! I've provided a bit of feedback to @shen-tian for the Piggieback setup, and I guess it applies here as well. I also have to familiarize a bit myself with workflows, as some of my feedback might be just promoted by the fact certain things look/feel weird to me.

**Comment by shen-tian** [comment]
Maybe it's best that we get one project right first? We can do nprel or piggieback. Then we can deal with the particular needs of each project.

**Comment by bbatsov** [comment]
Yeah, I agree. I like as a reference the setup outlined here https://github.com/clojure-emacs/cider/blob/master/.circleci/config.yml I think we should probably do nREPL first and take it from there.

**Comment by shen-tian** [comment]
@arichiardi : we got nrepl + piggieback done. So got a template there. Looking at the config here, it's all very similar. Main gotacha is the smoketest stuff: `make test smoketest` instead of just `make test`

**Comment by arichiardi** [comment]
Ok cool I will adjust the one in orchard

**Comment by shen-tian** [comment]
@arichiardi : you wanna finish this PR? Otherwise I can wrap it up.

**Comment by arichiardi** [comment]
@arichiardi if you have a bit of time I don't mind you finishing this, let me add you as collaborator of my fork :smile:

**Comment by bbatsov** [comment]
Any updates here?

**Comment by shen-tian** [comment]
Let me have a quick go at this now..

**Comment by shen-tian** [comment]
Merge once all ✅ and you are happy.

**Comment by bbatsov** [comment]
Looks good! Great work! 🙇

**Pull request merged**
